# Generated by Django 5.2.2 on 2025-08-19 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial'), ('tasks', '0002_alter_task_status'), ('tasks', '0003_alter_task_due_date'), ('tasks', '0004_alter_task_status'), ('tasks', '0005_tag'), ('tasks', '0006_telegramprofile'), ('tasks', '0007_alter_telegramprofile_chat_id'), ('tasks', '0008_telegramprofile_temp_token'), ('tasks', '0009_alter_telegramprofile_temp_token'), ('tasks', '0010_alter_telegramprofile_chat_id'), ('tasks', '0011_alter_task_status'), ('tasks', '0012_task_due_time'), ('tasks', '0013_alter_telegramprofile_user'), ('tasks', '0014_delete_telegramprofile')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('due_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tasks', models.ManyToManyField(related_name='tags', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
