# Generated by Django 5.2.2 on 2025-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'В очікуванні'), ('in_progress', 'Виконується'), ('completed', 'Виконано')], max_length=50),
        ),
    ]
