# Generated by Django 5.2.2 on 2025-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'В очікуванні'), ('in_progress', 'Виконується'), ('completed', 'Виконано')], default='pending', max_length=50),
        ),
    ]
