# Generated by Django 5.2.2 on 2025-07-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_telegramprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
