# Generated by Django 5.2.2 on 2025-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_telegramprofile_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='temp_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
