# Generated by Django 5.2.2 on 2025-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_telegramprofile_temp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='temp_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
