# Generated by Django 5.2.2 on 2025-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_telegramprofile_temp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
